type AffixType = 'prefix' | 'suffix';

export interface Affix {
  type: AffixType;
  func: string;
  name: string;
  stat: string;
  items?: string;
}

export const AFFIXES: Affix[] = [
  { type: 'prefix', func: '攻擊準確率', name: '青銅 Bronze', stat: '+10-20 攻擊準確率' },
  { type: 'prefix', func: '攻擊準確率', name: '鐵 Iron', stat: '+21-40 攻擊準確率', items: '頭飾[4].武器[4].戒指[4]' },
  { type: 'prefix', func: '攻擊準確率', name: '鋼 Steel', stat: '+41-60 攻擊準確率', items: '頭飾[8].武器[8].戒指[8]' },
  { type: 'prefix', func: '攻擊準確率', name: '銀 Silver', stat: '+61-80 攻擊準確率', items: '頭飾[12].武器[12].戒指[12]' },
  { type: 'prefix', func: '攻擊準確率', name: '金 Gold', stat: '+81-100 攻擊準確率', items: '頭飾[17].武器[17].戒指[17]' },
  { type: 'prefix', func: '攻擊準確率', name: '白金 Platinum', stat: '+101-120 攻擊準確率', items: '頭飾[22].武器[22].戒指[22]' },
  { type: 'prefix', func: '攻擊準確率', name: '隕鐵 Meteoric', stat: '+121-150 攻擊準確率', items: '武器[27]' },
  { type: 'prefix', func: '攻擊準確率', name: '怪異 Strange', stat: '+151-300 攻擊準確率', items: '武器[32]' },
  { type: 'prefix', func: '攻擊準確率', name: '詭異 Weird', stat: '+301-450 攻擊準確率', items: '武器[37]' },
  { type: 'prefix', func: '攻擊準確率', name: '攻擊準確率-依角色等級決定', stat: '目光銳利 Hawkeye', items: '+6-594 攻擊準確率-依角色等級乘6' },
  { type: 'prefix', func: '冰冷傷害', name: '雪白 Snowy', stat: '+ 6-9 最小 19-30 最大冰冷傷害-冰凍持續1秒' },
  { type: 'prefix', func: '冰冷傷害', name: '顫抖 Shivering', stat: '+ 10-15 最小 31-45 最大冰冷傷害-冰凍持續2秒', items: '武器[35]' },
  { type: 'prefix', func: '冰冷傷害', name: '北風 Boreal', stat: '+ 16-23 最小 46-90 最大冰冷傷害-冰凍持續3秒', items: '武器[50]' },
  { type: 'prefix', func: '冰冷傷害', name: '嚴冬 Hibernal', stat: '+ 24-45 最小 91-140 最大冰冷傷害-冰凍持續4秒', items: '武器[70]' },
  { type: 'prefix', func: '火焰傷害', name: '烈火 Fiery', stat: '+ 16-25 最小 31-60 最大火焰傷害' },
  { type: 'prefix', func: '火焰傷害', name: '悶燒 Smoldering', stat: '+ 26-50 最小 61-90 最大火焰傷害', items: '武器[35]' },
  { type: 'prefix', func: '火焰傷害', name: '煙霧 Smoking', stat: '+ 51-80 最小 91-130 最大火焰傷害', items: '武器[41]' },
  { type: 'prefix', func: '火焰傷害', name: '燃燒 Flaming', stat: '+ 81-120 最小 131-180 最大火焰傷害', items: '武器[61]' },
  { type: 'prefix', func: '火焰傷害', name: '濃縮 Condensing', stat: '+ 121-170 最小 181-240 最大火焰傷害', items: '武器[77]' },
  { type: 'prefix', func: '閃電傷害', name: '靜態 Static', stat: '+1 最小 49-210 最大閃電傷害' },
  { type: 'prefix', func: '閃電傷害', name: '發光 Glowing', stat: '+1 最小 121-180 最大閃電傷害', items: '武器[34]' },
  { type: 'prefix', func: '閃電傷害', name: '嗡叫 Buzzing', stat: '+1 最小 181-260 最大閃電傷害', items: '武器[46]' },
  { type: 'prefix', func: '閃電傷害', name: '彎曲 Arcing', stat: '+1 最小 261-360 最大閃電傷害', items: '武器[60]' },
  { type: 'prefix', func: '閃電傷害', name: '震撼 Shocking', stat: '+1 最小 361-480 最大閃電傷害', items: '武器[76]' },
  { type: 'prefix', func: '毒素傷害', name: '腐敗 Septic', stat: '+6 毒素傷害-2秒間' },
  { type: 'prefix', func: '毒素傷害', name: '腐爛 Foul', stat: '+12 毒素傷害-3秒間', items: '武器[10]' },
  { type: 'prefix', func: '毒素傷害', name: '腐蝕 Corrosive', stat: '+80 毒素傷害-4秒間', items: '武器[20]' },
  { type: 'prefix', func: '毒素傷害', name: '劇毒 Toxic', stat: '+150 毒素傷害-5秒間', items: '武器[35]' },
  { type: 'prefix', func: '毒素傷害', name: '瘟疫 Pestilent', stat: '+275 毒素傷害-6秒間', items: '武器[50]' },
  { type: 'prefix', func: '傷害', name: '鋸齒 Jagged', stat: '+10-20% 傷害' },
  { type: 'prefix', func: '傷害', name: '致命 Deadly', stat: '+21-30% 傷害', items: '頭飾[5].武器[5]' },
  { type: 'prefix', func: '傷害', name: '惡毒 Vicious', stat: '+31-40% 傷害', items: '武器[8]' },
  { type: 'prefix', func: '傷害', name: '殘酷 Brutal', stat: '+41-50% 傷害', items: '武器[14]' },
  { type: 'prefix', func: '傷害', name: '穩重 Massive', stat: '+51-65% 傷害', items: '武器[20]' },
  { type: 'prefix', func: '傷害', name: '野蠻 Savage', stat: '+66-80% 傷害', items: '武器[26]' },
  { type: 'prefix', func: '傷害', name: '絕情 Merciless', stat: '+81-100% 傷害', items: '武器[32]' },
  { type: 'prefix', func: '傷害', name: '凶暴 Ferocious', stat: '+101-200% 傷害', items: '武器[41]' },
  { type: 'prefix', func: '傷害', name: '殘忍 Cruel', stat: '+201-300% 傷害', items: '武器[51]' },
  { type: 'prefix', func: '傷害', name: '額外攻擊準確率-依角色等級決定', stat: '幻影 Visionary', items: '+1-99% 額外攻擊準確率-依角色等級乘1' },
  { type: 'prefix', func: '傷害', name: '準確率/最大傷害-依角色等級決定', stat: '愚人 Fool\'s', items: '+16-1633 準確率/+0-49 最大傷害-依角色等級乘 16.5 / 0.5' },
  { type: 'prefix', func: '傷害', name: '尖叫 Grinding', stat: '+0-74 最大傷害-依角色等級乘0.75', items: '武器[50]' },
  { type: 'prefix', func: '傷害', name: '攻擊準確率/傷害', stat: '尖銳 Sharp', items: '+10-20 攻擊準確率 +10-20% 傷害' },
  { type: 'prefix', func: '傷害', name: '精良 Fine', stat: '+21-40 攻擊準確率 +21-30% 傷害', items: '武器[12]' },
  { type: 'prefix', func: '傷害', name: '戰士 Warrior\'s', stat: '+41-60 攻擊準確率 +31-40% 傷害', items: '武器[19]' },
  { type: 'prefix', func: '傷害', name: '士兵 Soldier\'s', stat: '+61-80 攻擊準確率 +41-50% 傷害', items: '武器[27]' },
  { type: 'prefix', func: '傷害', name: '騎士 Knight\'s', stat: '+81-100 攻擊準確率 +51-65% 傷害', items: '武器[38]' },
  { type: 'prefix', func: '傷害', name: '君王 Lord\'s', stat: '+101-120 攻擊準確率 +66-80% 傷害', items: '武器[47]' },
  { type: 'prefix', func: '傷害', name: '國王 King\'s', stat: '+121-150 攻擊準確率 +81-100% 傷害', items: '武器[56]' },
  { type: 'prefix', func: '傷害', name: '大師 Master\'s', stat: '+151-250 攻擊準確率 +101-150% 傷害', items: '武器[56]' },
  { type: 'prefix', func: '傷害', name: '宗師 Grandmaster\'s', stat: '+251-300 攻擊準確率 +151-200% 傷害', items: '武器[69]' },
  { type: 'prefix', func: '額外對惡魔的攻擊準確率.傷害', name: '月精靈 Lunar', stat: '對抗惡魔額外+25-50 攻擊準確率 傷害+10-25%' },
  { type: 'prefix', func: '額外對惡魔的攻擊準確率.傷害', name: '田園 Arcadian', stat: '對抗惡魔額外+51-100 攻擊準確率 傷害+26-50%', items: '頭飾[15].武器[15]' },
  { type: 'prefix', func: '額外對惡魔的攻擊準確率.傷害', name: '超自然 Unearthly', stat: '對抗惡魔額外+101-150 攻擊準確率 傷害+51-100%', items: '武器[25]' },
  { type: 'prefix', func: '額外對惡魔的攻擊準確率.傷害', name: '星間 Astral', stat: '對抗惡魔額外+151-200 攻擊準確率 傷害+101-150%', items: '武器[35]' },
  { type: 'prefix', func: '額外對惡魔的攻擊準確率.傷害', name: '極樂 Elysian', stat: '對抗惡魔額外+201-300 攻擊準確率 傷害+151-200%', items: '武器[45]' },
  { type: 'prefix', func: '額外對惡魔的攻擊準確率.傷害', name: '天體 Celestial', stat: '對抗惡魔額外+300-400 攻擊準確率 傷害+201-300%', items: '武器[55]' },
  { type: 'prefix', func: '額外對不死生物的攻擊準確率.傷害', name: '淨化 Consecrated', stat: '對抗不死生物額外+25-75 攻擊準確率 傷害+25-75%' },
  { type: 'prefix', func: '額外對不死生物的攻擊準確率.傷害', name: '純潔 Pure', stat: '對抗不死生物額外+76-175 攻擊準確率 傷害+76-125%', items: '武器[15]' },
  { type: 'prefix', func: '額外對不死生物的攻擊準確率.傷害', name: '神聖 Sacred', stat: '對抗不死生物額外+175-250 攻擊準確率 傷害+126-200%', items: '武器[25]' },
  { type: 'prefix', func: '額外對不死生物的攻擊準確率.傷害', name: '聖潔 Hallowed', stat: '對抗不死生物額外+251-325 攻擊準確率 傷害+201-275%', items: '武器[35]' },
  { type: 'prefix', func: '額外對不死生物的攻擊準確率.傷害', name: '神性 Divine', stat: '對抗不死生物額外+326-450 攻擊準確率 傷害+276-350%', items: '武器[55]' },
  { type: 'prefix', func: '防禦', name: '結實 Sturdy', stat: '+10-30% 防禦' },
  { type: 'prefix', func: '防禦', name: '強壯 Strong', stat: '+31-40% 防禦', items: '防具[9]' },
  { type: 'prefix', func: '防禦', name: '光榮 Glorious', stat: '+41-50% 防禦', items: '防具[19]' },
  { type: 'prefix', func: '防禦', name: '祝福 Blessed', stat: '+51-65% 防禦', items: '防具[25]' },
  { type: 'prefix', func: '防禦', name: '崇高 Saintly', stat: '+66-80% 防禦', items: '防具[31]' },
  { type: 'prefix', func: '防禦', name: '神聖 Holy', stat: '+81-100% 防禦', items: '防具[36]' },
  { type: 'prefix', func: '防禦', name: '神 Godly', stat: '+101-200% 防禦', items: '防具[45]' },
  { type: 'prefix', func: '防禦', name: '防禦-依角色等級決定', stat: '忠誠 Faithful', items: '+3-297 防禦-依角色等級乘3' },
  { type: 'prefix', func: '防禦', name: '+0-49 防禦-依角色等級乘0.5', stat: '腰帶[30].鞋子[30].手套[30].盾牌[30]' },
  { type: 'prefix', func: '法力', name: '蜥蜴 Lizard\'s', stat: '+1-5 法力' },
  { type: 'prefix', func: '法力', name: '蛇 Snake\'s', stat: '+5-10 法力', items: '項鍊[6].腰帶[6].頭飾[6].戒指[6].棒類[6].盾牌[6]' },
  { type: 'prefix', func: '法力', name: '海蛇 Serpent\'s', stat: '+11-20 法力', items: '項鍊[14].腰帶[14].頭飾[14].戒指[14].棒類[14].盾牌[14].胸盔[37].鞋子[37].手套[37].武器[37]' },
  { type: 'prefix', func: '法力', name: '德爾克 Drake\'s', stat: '+21-30 法力', items: '項鍊[20].頭飾[20].法珠[20].戒指[20].棒類[20]' },
  { type: 'prefix', func: '法力', name: '龍 Dragon\'s', stat: '+31-40 法力', items: '項鍊[24].頭飾[24].法珠[24].戒指[24].棒類[24].胸盔[52].鞋子[52].手套[52]' },
  { type: 'prefix', func: '法力', name: '維特 Wyrm\'s', stat: '+41-60 法力', items: '項鍊[30].頭飾[30].法珠[30].戒指[30].棒類[30]' },
  { type: 'prefix', func: '法力', name: '巨飛龍 Great Wyrm\'s', stat: '+61-90 法力', items: '項鍊[37].頭飾[37].法珠[37].戒指[37].棒類[37]' },
  { type: 'prefix', func: '法力', name: '巴哈姆特 Bahamut\'s', stat: '+91-120 法力', items: '項鍊[45].頭飾[45].法珠[45].戒指[45].棒類[45]' },
  { type: 'prefix', func: '法力', name: '法力-依角色等級決定', stat: '記憶 Mnemonic', items: '+0-49 法力-依角色等級乘0.5' },
  { type: 'prefix', func: '照明', name: '微光 Glimmering', stat: '+1照亮範圍' },
  { type: 'prefix', func: '照明', name: '發光 Glowing', stat: '+2照亮範圍', items: '項鍊[6].防具[6].法珠[6].戒指[6].棍棒[6].法仗[6]' },
  { type: 'prefix', func: '抗火', name: '棗紅 Crimson', stat: '+5-10% 抗火' },
  { type: 'prefix', func: '抗火', name: '赤褐 Russet', stat: '+11-20% 抗火', items: '項鍊[12].防具[12].頭飾[12].法珠[12].戒指[12].武器[35]' },
  { type: 'prefix', func: '抗火', name: '深紅 Garnet', stat: '+21-30% 抗火', items: '項鍊[18].防具[18].頭飾[18].法珠[18].戒指[18].武器[55]' },
  { type: 'prefix', func: '抗火', name: '紅寶石 Ruby', stat: '+31-40% 抗火', items: '項鍊[25].防具[25].靴子[25].頭飾[25].法珠[25].戒指[25]' },
  { type: 'prefix', func: '抗冰', name: '天青 Azure', stat: '+5-10% 抗冰' },
  { type: 'prefix', func: '抗冰', name: '天藍 Lapis', stat: '+11-20% 抗冰', items: '項鍊[12].防具[12].頭飾[12].法珠[12].戒指[12].武器[35]' },
  { type: 'prefix', func: '抗冰', name: '鈷 Cobalt', stat: '+21-30% 抗冰', items: '項鍊[18].防具[18].頭飾[18].法珠[18].戒指[18].武器[55]' },
  { type: 'prefix', func: '抗冰', name: '蔚藍 Sapphire', stat: '+31-40% 抗冰', items: '項鍊[25].靴子[25].頭飾[25].法珠[25].棒類[25]' },
  { type: 'prefix', func: '抗電', name: '紅柑 Tangerine', stat: '+5-10% 抗電' },
  { type: 'prefix', func: '抗電', name: '赭黃 Ocher', stat: '+11-20% 抗電', items: '項鍊[12].防具[12].頭飾[12].法珠[12].戒指[12].武器[35]' },
  { type: 'prefix', func: '抗電', name: '珊瑚 Coral', stat: '+21-30% 抗電', items: '項鍊[18].防具[18].頭飾[18].法珠[18].戒指[18].武器[55]' },
  { type: 'prefix', func: '抗電', name: '琥珀 Amber', stat: '+31-40% 抗電', items: '項鍊[25].靴子[25].頭飾[25].法珠[25].棒類[25]' },
  { type: 'prefix', func: '抗毒', name: '海藍 Beryl', stat: '+5-10% 抗毒' },
  { type: 'prefix', func: '抗毒', name: '銘綠 Viridian', stat: '+11-20% 抗毒', items: '項鍊[12].防具[12].頭飾[12].法珠[12].戒指[12].武器[35]' },
  { type: 'prefix', func: '抗毒', name: '翠綠 Jade', stat: '+21-30% 抗毒', items: '項鍊[18].防具[18].頭飾[18].法珠[18].戒指[18].武器[55]' },
  { type: 'prefix', func: '抗毒', name: '祖母綠 Emerald', stat: '+31-40% 抗毒', items: '項鍊[25].靴子[25].頭飾[25].法珠[25].棒類[25]' },
  { type: 'prefix', func: '全抗', name: '閃耀 Shimmering', stat: '+3-7% 全抗' },
  { type: 'prefix', func: '全抗', name: '彩虹 Rainbow', stat: '+8-11% 全抗', items: '盾牌[18].項鍊[21].頭飾[21].戒指[56]' },
  { type: 'prefix', func: '全抗', name: '閃閃發光 Scintillating', stat: '+12-15% 全抗', items: '盾牌[28].項鍊[34].頭飾[34].戒指[67]' },
  { type: 'prefix', func: '全抗', name: '棱鏡 Prismatic', stat: '+16-20% 全抗', items: '盾牌[39].項鍊[42].頭飾[42]' },
  { type: 'prefix', func: '全抗', name: '多彩 Chromatic', stat: '+21-30% 全抗', items: '盾牌[50].項鍊[55].頭飾[55]' },
  { type: 'prefix', func: '職業全技能', name: '處女 Maiden\'s', stat: '+1亞馬遜技能' },
  { type: 'prefix', func: '職業全技能', name: '女武神 Valkyrie\'s', stat: '+2亞馬遜技能', items: '弓[50].十字弓[50].標槍[30].長矛[50].項鍊[90].頭飾[90]' },
  { type: 'prefix', func: '職業全技能', name: '屠殺者 Slayer', stat: '+1野蠻人技能', items: '斧[30].野蠻人專用頭盔[30].木棒[30].錘[30].標槍[30].匕首[30].釘槌[30].投擲武器[30].長矛[30].劍[30].項鍊[36].頭飾[36]' },
  { type: 'prefix', func: '職業全技能', name: '狂戰士 Berserker', stat: '+2野蠻人技能', items: '斧[50].野蠻人專用頭盔[50].木棒[50].錘[50].標槍[50].匕首[50].釘槌[50].投擲武器[50].長矛[50].劍[50].項鍊[90].頭飾[90]' },
  { type: 'prefix', func: '職業全技能', name: '僧人 Monk\'s', stat: '+1聖騎士技能', items: '聖騎士專用盾牌[30].權杖[30].錘[35].釘槌[35].盾牌[35].劍[35].項鍊[36].頭飾[36]' },
  { type: 'prefix', func: '職業全技能', name: '牧師 Priest\'s', stat: '+2聖騎士技能', items: '聖騎士專用盾牌[50].權杖[50].錘[60].釘槌[60].盾牌[60].劍[60].項鍊[90].頭飾[90]' },
  { type: 'prefix', func: '職業全技能', name: '照喚者 Summoner\'s', stat: '+1死靈法師技能', items: '頭戴[30].匕首[30].魔仗[30].項鍊[36].頭飾[36]' },
  { type: 'prefix', func: '職業全技能', name: '死靈法師 Necromancer\'s', stat: '+2死靈法師技能', items: '頭戴[50].匕首[50].魔仗[50].項鍊[90].頭飾[90]' },
  { type: 'prefix', func: '職業全技能', name: '天使 Angel\'s', stat: '+1法師技能', items: '法珠[30].法仗[30].項鍊[36].頭飾[36]' },
  { type: 'prefix', func: '職業全技能', name: '大天使 Arch-Angel\'s', stat: '+2法師技能', items: '法珠[50].法仗[50].項鍊[90].頭飾[90]' },
  { type: 'prefix', func: '職業全技能', name: '巫師 Shaman\'s', stat: '+1德魯伊技能', items: '木棒[30].德魯伊專用頭盔[30].項鍊[36].頭飾[36]' },
  { type: 'prefix', func: '職業全技能', name: '祭師 Hierophant\'s', stat: '+2德魯伊技能', items: '木棒[50].德魯伊專用頭盔[50].項鍊[90].頭飾[90]' },
  { type: 'prefix', func: '職業全技能', name: '法師殺手 Magekiller\'s', stat: '+1刺客技能', items: '刺客專用爪[30].項鍊[36].頭飾[36]' },
  { type: 'prefix', func: '職業全技能', name: '女巫獵人 Witch-hunter\'s', stat: '+2刺客技能', items: '刺客專用爪[50].項鍊[90].頭飾[90]' },
  { type: 'prefix', func: '亞馬遜技能', name: '製箭者 Fletcher\'s', stat: '+1亞馬遜弓與十字弓技能' },
  { type: 'prefix', func: '亞馬遜技能', name: '製弓匠 Bowyer\'s', stat: '+2亞馬遜弓與十字弓技能', items: '弓[40].十字弓[40].手套[40]' },
  { type: 'prefix', func: '亞馬遜技能', name: '弓箭手 Archer\'s', stat: '+3亞馬遜弓與十字弓技能', items: '弓[60].十字弓[60].手套[60]' },
  { type: 'prefix', func: '亞馬遜技能', name: '特技 Acrobat\'s', stat: '+1亞馬遜被動與魔法技能', items: '項鍊[20].頭飾[20].手套[20]' },
  { type: 'prefix', func: '亞馬遜技能', name: '體技 Gymnast\'s', stat: '+2亞馬遜被動與魔法技能', items: '項鍊[40].頭飾[40].手套[40]' },
  { type: 'prefix', func: '亞馬遜技能', name: '競賽 Athlete\'s', stat: '+3亞馬遜被動與魔法技能', items: '項鍊[60].頭飾[60].手套[60]' },
  { type: 'prefix', func: '亞馬遜技能', name: '魚叉手 Harpoonist\'s', stat: '+1亞馬遜標槍與長矛技能', items: '手套[20].長矛[20]' },
  { type: 'prefix', func: '亞馬遜技能', name: '女矛手 Spearmaiden\'s', stat: '+2亞馬遜標槍與長矛技能', items: '手套[40].長矛[40]' },
  { type: 'prefix', func: '亞馬遜技能', name: '長槍兵 Lancer\'s', stat: '+3亞馬遜標槍與長矛技能', items: '手套[60].長矛[60]' },
  { type: 'prefix', func: '法師技能', name: '燃燒 Burning', stat: '+1法師火焰系技能' },
  { type: 'prefix', func: '法師技能', name: '炎熱 Blazing', stat: '+2法師火焰系技能', items: '項鍊[40].頭飾[40].法珠[40].法仗[40]' },
  { type: 'prefix', func: '法師技能', name: '火山Volcanic', stat: '+3法師火焰系技能', items: '項鍊[60].頭飾[60].法珠[60].法仗[60]' },
  { type: 'prefix', func: '法師技能', name: '火光 Sparking', stat: '+1法師閃電系技能', items: '項鍊[20].頭飾[20].法珠[20].法仗[20]' },
  { type: 'prefix', func: '法師技能', name: '充能 Charged', stat: '+2法師閃電系技能', items: '項鍊[40].頭飾[40].法珠[40].法仗[40]' },
  { type: 'prefix', func: '法師技能', name: '力量十足 Powered', stat: '+3法師閃電系技能', items: '項鍊[60].頭飾[60].法珠[60].法仗[60]' },
  { type: 'prefix', func: '法師技能', name: '寒意 Chilling', stat: '+1法師冰冷系技能', items: '項鍊[20].頭飾[20].法珠[20].法仗[20]' },
  { type: 'prefix', func: '法師技能', name: '冰凍 Freezing', stat: '+2法師冰冷系技能', items: '項鍊[40].頭飾[40].法珠[40].法仗[40]' },
  { type: 'prefix', func: '法師技能', name: '冰冷 Glacial', stat: '+3法師冰冷系技能', items: '項鍊[60].頭飾[60].法珠[60].法仗[60]' },
  { type: 'prefix', func: '死靈法師技能', name: '詛咒 Hexing', stat: '+1死靈法師詛咒技能' },
  { type: 'prefix', func: '死靈法師技能', name: '枯萎 Blighting', stat: '+2死靈法師詛咒技能', items: '項鍊[40].頭飾[40].頭戴[40].魔仗[40]' },
  { type: 'prefix', func: '死靈法師技能', name: '詛咒 Accursed', stat: '+3死靈法師詛咒技能', items: '項鍊[60].頭飾[60].頭戴[60].魔仗[60]' },
  { type: 'prefix', func: '死靈法師技能', name: '黴菌 Fungal', stat: '+1死靈法師毒素與白骨技能', items: '項鍊[20].頭飾[20].頭戴[20].匕首[20].魔仗[20]' },
  { type: 'prefix', func: '死靈法師技能', name: '有害 Noxious', stat: '+2死靈法師毒素與白骨技能', items: '項鍊[40].頭飾[40].頭戴[40].匕首[40].魔仗[40]' },
  { type: 'prefix', func: '死靈法師技能', name: '劇毒 Venomous', stat: '+3死靈法師毒素與白骨技能', items: '項鍊[60].頭飾[60].頭戴[60].匕首[60].魔仗[60]' },
  { type: 'prefix', func: '死靈法師技能', name: '盜墓者 Graverobber\'s', stat: '+1死靈法師召喚技能', items: '項鍊[20].頭飾[20].頭戴[20].魔仗[20]' },
  { type: 'prefix', func: '死靈法師技能', name: '雄壯 Mojo', stat: '+2死靈法師召喚技能', items: '項鍊[40].頭飾[40].頭戴[40].魔仗[40]' },
  { type: 'prefix', func: '死靈法師技能', name: '石魔之王 Golemlord\'s', stat: '+3死靈法師召喚技能', items: '項鍊[60].頭飾[60].頭戴[60].魔仗[60]' },
  { type: 'prefix', func: '聖騎士技能', name: '獅子烙印 Lion Branded', stat: '+1聖騎士戰鬥技能' },
  { type: 'prefix', func: '聖騎士技能', name: '老鷹烙印 Hawk Branded', stat: '+2聖騎士戰鬥技能', items: '項鍊[40].頭飾[40].釘槌[40].聖騎士專用盾[40].權杖[40].盾牌[40].劍[40]' },
  { type: 'prefix', func: '聖騎士技能', name: '玫瑰烙印 Rose Branded', stat: '+3聖騎士戰鬥技能', items: '項鍊[60].頭飾[60].釘槌[60].聖騎士專用盾[60].權杖[60].盾牌[60].劍[60]' },
  { type: 'prefix', func: '聖騎士技能', name: '隊長 Captain\'s', stat: '+1聖騎士攻擊性靈氣技能', items: '項鍊[20].頭飾[20].釘槌[20].聖騎士專用盾[20].權杖[20].盾牌[20].劍[20]' },
  { type: 'prefix', func: '聖騎士技能', name: '指揮官 Commander\'s', stat: '+2聖騎士攻擊性靈氣技能', items: '項鍊[40].頭飾[40].釘槌[40].聖騎士專用盾[40].權杖[40].盾牌[40].劍[40]' },
  { type: 'prefix', func: '聖騎士技能', name: '元帥 Marshal\'s', stat: '+3聖騎士攻擊性靈氣技能', items: '項鍊[60].頭飾[60].釘槌[60].聖騎士專用盾[60].權杖[60].盾牌[60].劍[60]' },
  { type: 'prefix', func: '聖騎士技能', name: '保護者 Preserver\'s', stat: '+1聖騎士防禦性靈氣技能', items: '項鍊[20].頭飾[20].聖騎士專用盾[20].盾牌[20].' },
  { type: 'prefix', func: '聖騎士技能', name: '主管 Warder\'s', stat: '+2聖騎士防禦性靈氣技能', items: '項鍊[40].頭飾[40].聖騎士專用盾[40].盾牌[40].' },
  { type: 'prefix', func: '聖騎士技能', name: '守護者 Guardian\'s', stat: '+3聖騎士防禦性靈氣技能', items: '項鍊[60].頭飾[60].聖騎士專用盾[60].盾牌[60].' },
  { type: 'prefix', func: '野蠻人技能', name: '專家 Expert\'s', stat: '+1野蠻人戰鬥技能' },
  { type: 'prefix', func: '野蠻人技能', name: '老手 Veteran\'s', stat: '+2野蠻人戰鬥技能', items: '野蠻人專用頭盔[40].頭盔[40].武器[40]' },
  { type: 'prefix', func: '野蠻人技能', name: '大師 Master\'s', stat: '+3野蠻人戰鬥技能', items: '野蠻人專用頭盔[60].頭盔[60].武器[60]' },
  { type: 'prefix', func: '野蠻人技能', name: '狂信者 Fanatic', stat: '+1野蠻人支配性技能', items: '項鍊[20].野蠻人專用頭盔[20].武器[20]' },
  { type: 'prefix', func: '野蠻人技能', name: '猛烈 Raging', stat: '+2野蠻人支配性技能', items: '項鍊[40].野蠻人專用頭盔[40].武器[40]' },
  { type: 'prefix', func: '野蠻人技能', name: '狂怒 Furious', stat: '+3野蠻人支配性技能', items: '項鍊[60].野蠻人專用頭盔[60].武器[60]' },
  { type: 'prefix', func: '野蠻人技能', name: '鳴響 Sounding', stat: '+1野蠻人戰嚎技能', items: '項鍊[20].野蠻人專用頭盔[20].武器[20]' },
  { type: 'prefix', func: '野蠻人技能', name: '迴響 Resonant', stat: '+2野蠻人戰嚎技能', items: '項鍊[40].野蠻人專用頭盔[40].武器[40]' },
  { type: 'prefix', func: '野蠻人技能', name: '回音 Echoing', stat: '+3野蠻人戰嚎技能', items: '項鍊[60].野蠻人專用頭盔[60].武器[60]' },
  { type: 'prefix', func: '德魯伊技能', name: '訓練師 Trainer\'s', stat: '+1德魯伊召喚技能' },
  { type: 'prefix', func: '德魯伊技能', name: '看守人 Caretaker\'s', stat: '+2德魯伊召喚技能', items: '項鍊[40].頭飾[40].木棒[40].德魯伊專用頭盔[40]' },
  { type: 'prefix', func: '德魯伊技能', name: '管理者 Keeper\'s', stat: '+3德魯伊召喚技能', items: '項鍊[60].頭飾[60].木棒[60].德魯伊專用頭盔[60]' },
  { type: 'prefix', func: '德魯伊技能', name: '精神 Spiritual', stat: '+1德魯伊變形技能', items: '項鍊[20].頭飾[20].木棒[20].德魯伊專用頭盔[20]' },
  { type: 'prefix', func: '德魯伊技能', name: '猛禽 Feral', stat: '+2德魯伊變形技能', items: '項鍊[40].頭飾[40].木棒[40].德魯伊專用頭盔[40]' },
  { type: 'prefix', func: '德魯伊技能', name: '共有 Communal', stat: '+3德魯伊變形技能', items: '項鍊[60].頭飾[60].木棒[60].德魯伊專用頭盔[60]' },
  { type: 'prefix', func: '德魯伊技能', name: '自然 Nature\'s', stat: '+1德魯伊元素技能', items: '項鍊[20].頭飾[20].木棒[20].德魯伊專用頭盔[20]' },
  { type: 'prefix', func: '德魯伊技能', name: '祭司 Terra\'s', stat: '+2德魯伊元素技能', items: '項鍊[40].頭飾[40].木棒[40].德魯伊專用頭盔[40]' },
  { type: 'prefix', func: '德魯伊技能', name: '蓋亞 Gaea\'s', stat: '+3德魯伊元素技能', items: '項鍊[60].頭飾[60].木棒[60].德魯伊專用頭盔[60]' },
  { type: 'prefix', func: '刺客技能', name: '誘騙 Entrapping', stat: '+1刺客陷阱技能' },
  { type: 'prefix', func: '刺客技能', name: '欺詐 Trickster\'s', stat: '+2刺客陷阱技能', items: '項鍊[40].頭飾[40].刺客專用爪[40]' },
  { type: 'prefix', func: '刺客技能', name: '冷靜 Cunning', stat: '+3刺客陷阱技能', items: '項鍊[60].頭飾[60].刺客專用爪[60]' },
  { type: 'prefix', func: '刺客技能', name: '心智 Mentalist\'s', stat: '+1刺客影子訓練技能', items: '項鍊[20].頭飾[20].頭盔[20].刺客專用爪[20]' },
  { type: 'prefix', func: '刺客技能', name: '心靈 Psychic', stat: '+2刺客影子訓練技能', items: '項鍊[40].頭飾[40].頭盔[40].刺客專用爪[40]' },
  { type: 'prefix', func: '刺客技能', name: '陰影 Shadow', stat: '+3刺客影子訓練技能', items: '項鍊[60].頭飾[60].頭盔[60].刺客專用爪[60]' },
  { type: 'prefix', func: '刺客技能', name: '將軍 Shogukusha\'s', stat: '+1刺客武學藝術技能', items: '項鍊[20].頭飾[20].頭盔[20].刺客專用爪[20]' },
  { type: 'prefix', func: '刺客技能', name: '劍士 Sensei\'s', stat: '+2刺客武學藝術技能', items: '項鍊[40].頭飾[40].頭盔[40].刺客專用爪[40]' },
  { type: 'prefix', func: '刺客技能', name: '劍聖 Kenshi\'s', stat: '+3刺客武學藝術技能', items: '項鍊[60].頭飾[60].頭盔[60].刺客專用爪[60]' },
  { type: 'prefix', func: '受損傷害移至法力', name: '奸詐 Vulpine', stat: '7-12% 受損的生命移至法力' },
  { type: 'prefix', func: '每殺一個敵人後取得法力', name: '成功 Triumphant', stat: '+1 法力在每殺一個敵人後取得' },
  { type: 'prefix', func: '每殺一個敵人後取得法力', name: '優勝 Victorious', stat: '+2-5 法力在每殺一個敵人後取得', items: '頭飾[17].武器[17]' },
  { type: 'prefix', func: '更佳的機會取得魔法裝備', name: '得體 Felicitous', stat: '+5-10% 更佳的機會取得魔法裝備' },
  { type: 'prefix', func: '更佳的機會取得魔法裝備', name: '偶然 Fortuitous', stat: '+11-15% 更佳的機會取得魔法裝備', items: '項鍊[12].頭飾[12].戒指[12]' },
  { type: 'prefix', func: '增加最大耐力', name: '凹凸 Rugged', stat: '+5-20 最大耐力' },
  { type: 'prefix', func: '增加最大耐力', name: '活力 Vigorous', stat: '+21-30 最大耐力', items: '腰帶[16].鞋子[16]' },
  { type: 'prefix', func: '回覆耐力', name: '不倦 Tireless', stat: '耐力回復 +25-50%' },
  { type: 'prefix', func: '擊中使怪物逃跑', name: '尖叫 Screaming', stat: '擊中使怪物逃跑12-25%[16-32]' },
  { type: 'prefix', func: '擊中使怪物逃跑', name: '咆哮 Howling', stat: '擊中使怪物逃跑18-50%[24-64]', items: '弓(24)[16].十字弓(24)[16].武器(64)[16]' },
  { type: 'prefix', func: '擊中使怪物逃跑', name: '哭號 Wailing', stat: '擊中使怪物逃跑25-100%[32-128]', items: '弓(32)[24].十字弓(32)[24].武器(128)[20]' },
  { type: 'prefix', func: '增加凹槽', name: '技工 Mechanic\'s', stat: '增加1-2個凹槽' },
  { type: 'prefix', func: '增加凹槽', name: '工匠 Artisan\'s', stat: '增加3個凹槽', items: '胸盔[33].頭飾[33].頭盔[33].盾牌[33].武器[33]' },
  { type: 'prefix', func: '增加凹槽', name: '珠寶匠 Jeweler\'s', stat: '增加4個凹槽', items: '胸盔[55].頭飾[55].頭盔[55].盾牌[55].武器[55]' },
  { type: 'prefix', func: '增加投擲武器數量', name: '密實 Compact', stat: '+20-40 數量' },
  { type: 'prefix', func: '增加投擲武器數量', name: '細瘦 Thin', stat: '+41-80 數量', items: '投擲類武器[17]' },
  { type: 'prefix', func: '增加投擲武器數量', name: '密集 Dense', stat: '+80-120 數量', items: '投擲類武器[38]' },
  { type: 'suffix', func: '力量', name: '力量 Strength', stat: '+1-2 力量' },
  { type: 'suffix', func: '力量', name: '武力 Might', stat: '+3-5 力量', items: '項鍊[10].腰帶[10].頭飾[10].木棒[10].錘[10].胸盔[21].釘槌[21].戒指[21].權杖[21].手套[33].近身武器[33].盾牌[33]' },
  { type: 'suffix', func: '力量', name: '公牛 Ox', stat: '+6-9 力量', items: '項鍊[26].腰帶[26].頭飾[26].木棒[26].錘[26].胸盔[38].釘槌[38].戒指[38].權杖[38].手套[45].近身武器[45].盾牌[45]' },
  { type: 'suffix', func: '力量', name: '巨人 Giant', stat: '+10-15 力量', items: '項鍊[42].腰帶[42].頭飾[42].木棒[42].錘[42].胸盔[55].釘槌[55].戒指[55].權杖[55].手套[59].近身武器[59]' },
  { type: 'suffix', func: '力量', name: '泰坦 Titan', stat: '+16-20 力量', items: '項鍊[58].腰帶[58].頭飾[58].木棒[58].錘[58].胸盔[74].釘槌[74].戒指[74].權杖[74]' },
  { type: 'suffix', func: '力量', name: '擎天神 Atlas', stat: '+21-30 力量', items: '項鍊[71].腰帶[71].頭飾[71].木棒[71].錘[71]' },
  { type: 'suffix', func: '敏捷', name: '敏捷 Dexterity', stat: '+1-2 敏捷' },
  { type: 'suffix', func: '敏捷', name: '技能 Skill', stat: '+3-5 敏捷', items: '項鍊[11].弓[11].頭飾[11].十字弓[11].手套[22].戒指[22].胸盔[34].鞋子[34]' },
  { type: 'suffix', func: '敏捷', name: '準確 Accuracy', stat: '+6-9 敏捷', items: '項鍊[27].弓[27].頭飾[27].十字弓[27].手套[39].戒指[39].胸盔[46].鞋子[46]' },
  { type: 'suffix', func: '敏捷', name: '精密 Precision', stat: '+10-15 敏捷', items: '項鍊[43].弓[43].頭飾[43].十字弓[43].手套[56].戒指[56].胸盔[60].鞋子[60]' },
  { type: 'suffix', func: '敏捷', name: '完美 Perfection', stat: '+16-20 敏捷', items: '項鍊[59].弓[59].頭飾[59].十字弓[59].手套[75].戒指[75]' },
  { type: 'suffix', func: '敏捷', name: '涅盤 Nirvana', stat: '+21-30 敏捷', items: '項鍊[72].弓[72].頭飾[72].十字弓[72]' },
  { type: 'suffix', func: '精力', name: '能源 Energy', stat: '+1-3 精力' },
  { type: 'suffix', func: '精力', name: '思想 Mind', stat: '+4-6 精力', items: '項鍊[7].頭飾[7].法珠[7].法仗[7].魔仗[7].頭盔[10].權杖[10].戒指[13]' },
  { type: 'suffix', func: '精力', name: '才能 Brilliance', stat: '+7-10 精力', items: '項鍊[13].頭飾[13].法珠[13].法仗[13].魔仗[13].頭盔[16].權杖[16].戒指[21]' },
  { type: 'suffix', func: '精力', name: '幻術 Sorcery', stat: '+11-15 精力', items: '項鍊[21].頭飾[21].法珠[21].法仗[21].魔仗[21].頭盔[26].權杖[26].戒指[31]' },
  { type: 'suffix', func: '精力', name: '法術 Wizardry', stat: '+16-20 精力', items: '項鍊[31].頭飾[31].法珠[31].法仗[31].魔仗[31].戒指[31]' },
  { type: 'suffix', func: '精力', name: '啟發 Enlightenment', stat: '+21-30 精力', items: '項鍊[41].頭飾[41].法珠[41].法仗[41].魔仗[41]' },
  { type: 'suffix', func: '生命', name: '財狼 Jackal', stat: '+1-5 生命' },
  { type: 'suffix', func: '生命', name: '狐狸 Fox', stat: '+6-10 生命', items: '項鍊[7].野蠻人專用頭盔[7].腰帶[7].胸盔[7].頭飾[7].德魯伊專用頭盔[11].盾牌[11].木棒[17].錘[17].頭盔[17].釘槌[17].戒指[17]' },
  { type: 'suffix', func: '生命', name: '狼 Wolf', stat: '+11-20 生命', items: '項鍊[15].野蠻人專用頭盔[15].腰帶[15].胸盔[15].頭飾[15].德魯伊專用頭盔[11].盾牌[11].木棒[17].錘[17].頭盔[17].釘槌[17].戒指[17]' },
  { type: 'suffix', func: '生命', name: '虎 Tiger', stat: '+21-30 生命', items: '項鍊[20].野蠻人專用頭盔[20].腰帶[20].胸盔[20].頭飾[20].德魯伊專用頭盔[43].盾牌[51].木棒[51].錘[51].頭盔[51].釘槌[51].戒指[51]' },
  { type: 'suffix', func: '生命', name: '巨大 Mammoth', stat: '+31-40 生命', items: '項鍊[20].野蠻人專用頭盔[20].腰帶[20].胸盔[20].頭飾[20].德魯伊專用頭盔[59].盾牌[59].木棒[68].錘[68].頭盔[68].釘槌[68].戒指[68]' },
  { type: 'suffix', func: '生命', name: '巨神 Gargantuan', stat: '+41-60 生命', items: '項鍊[30].野蠻人專用頭盔[30].腰帶[30].胸盔[30].頭飾[30].德魯伊專用頭盔[75].盾牌[75]' },
  { type: 'suffix', func: '生命', name: '烏賊 Squid', stat: '+61-80 生命', items: '項鍊[40].野蠻人專用頭盔[40].腰帶[40].胸盔[40].頭飾[40]' },
  { type: 'suffix', func: '生命', name: '巨鯨 Whale', stat: '+81-100 生命', items: '項鍊[50].野蠻人專用頭盔[50].腰帶[50].胸盔[50].頭飾[50]' },
  { type: 'suffix', func: '照明與攻擊準確率', name: '光明 Light', stat: '+1照亮範圍,+15攻擊準確率' },
  { type: 'suffix', func: '照明與攻擊準確率', name: '光彩 Radiance', stat: '+3照亮範圍,+30攻擊準確率', items: '項鍊[15].弓[15].十字弓[15].頭盔[15].戒指[15].棒類[15]' },
  { type: 'suffix', func: '照明與攻擊準確率', name: '太陽 Sun', stat: '+5照亮範圍,+5%額外攻擊準確率', items: '項鍊[17].弓[17].十字弓[17].手套[17].頭盔[17].戒指[17].棒類[17]' },
  { type: 'suffix', func: '最小傷害', name: '價值 Worth', stat: '+1-2 最小傷害值' },
  { type: 'suffix', func: '最小傷害', name: '測量 Measure', stat: '+3-4 最小傷害值', items: '武器[12].項鍊[37].頭飾[37].戒指[37]' },
  { type: 'suffix', func: '最小傷害', name: '精靈 Excellence', stat: '+5-8 最小傷害值', items: '武器[24].項鍊[59].頭飾[59].戒指[59]' },
  { type: 'suffix', func: '最小傷害', name: '表現 Performance', stat: '+9-14 最小傷害值', items: '武器[48].項鍊[81].頭飾[81].戒指[81]' },
  { type: 'suffix', func: '最小傷害', name: '超凡 Transcendence', stat: '+15-20 最小傷害值', items: '戒指[76]' },
  { type: 'suffix', func: '最大傷害', name: '工匠 Craftsmanship', stat: '+1 最大傷害值' },
  { type: 'suffix', func: '最大傷害', name: '品質 Quality', stat: '+2 最大傷害值', items: '武器[4]' },
  { type: 'suffix', func: '最大傷害', name: '殘廢 Maiming', stat: '+3-4 最大傷害值', items: '項鍊[42].戒指[42].武器[7].盾牌[42]' },
  { type: 'suffix', func: '最大傷害', name: '屠殺 Slaying', stat: '+5-7 最大傷害值', items: '武器[11]' },
  { type: 'suffix', func: '最大傷害', name: '凝血 Gore', stat: '+8-10 最大傷害值', items: '武器[14]' },
  { type: 'suffix', func: '最大傷害', name: '屠殺 Carnage', stat: '+11-14 最大傷害值', items: '武器[19]' },
  { type: 'suffix', func: '最大傷害', name: '殘殺 Slaughter', stat: '+15-20 最大傷害值', items: '武器[25]' },
  { type: 'suffix', func: '最大傷害', name: '屠殺 Butchery', stat: '+21-40 最大傷害值', items: '武器[35]' },
  { type: 'suffix', func: '最大傷害', name: '吸精 Evisceration', stat: '+41-63 最大傷害值', items: '武器[45]' },
  { type: 'suffix', func: '火焰傷害', name: '火焰 Flame', stat: '+1 最小和 2-6 最大火焰傷害' },
  { type: 'suffix', func: '火焰傷害', name: '火 Fire', stat: '+1-4 最小和 6-11 最大火焰傷害', items: '武器[15]' },
  { type: 'suffix', func: '火焰傷害', name: '燃燒 Burning', stat: '+5-9 最小和 10-20 最大火焰傷害', items: '武器[25]' },
  { type: 'suffix', func: '火焰傷害', name: '熾炎 Incineration', stat: '+10-15 最小和 21-75 最大火焰傷害', items: '武器[32]' },
  { type: 'suffix', func: '冰冷傷害', name: '霜 Frost', stat: '+1 最小和 1-2 最大冰冷傷害-持續時間2秒' },
  { type: 'suffix', func: '冰冷傷害', name: '冰刺 Icicle', stat: '+1 最小和 3-4 最大冰冷傷害-持續時間3秒', items: '武器[13]' },
  { type: 'suffix', func: '冰冷傷害', name: '冰河 Glacier', stat: '+2-4 最小和 4-15 最大冰冷傷害-持續時間4秒', items: '近戰類武器[27]' },
  { type: 'suffix', func: '冰冷傷害', name: '嚴冬 Winter', stat: '+5-9 最小和 16-50 最大冰冷傷害-持續時間5秒', items: '近戰類武器[30]' },
  { type: 'suffix', func: '閃電傷害', name: '衝擊 Shock', stat: '+1 最小和 6-8 最大閃電傷害' },
  { type: 'suffix', func: '閃電傷害', name: '閃電 Lightning', stat: '+1 最小和 9-16 最大閃電傷害', items: '武器[15]' },
  { type: 'suffix', func: '閃電傷害', name: '雷電 Thunder', stat: '+1 最小和 17-40 最大閃電傷害', items: '武器[25]' },
  { type: 'suffix', func: '閃電傷害', name: '暴風 Storms', stat: '+1-6 最小和 40-120 最大閃電傷害', items: '武器[34]' },
  { type: 'suffix', func: '毒素傷害', name: '枯萎 Blight', stat: '+50 毒素傷害於3秒內' },
  { type: 'suffix', func: '毒素傷害', name: '毒素 Venom', stat: '+3-9 毒素傷害於2秒內', items: '頭飾[15].武器[15]' },
  { type: 'suffix', func: '毒素傷害', name: '瘟疫 Pestilence', stat: '+6-14 毒素傷害於2秒內', items: '頭飾[25].武器[25]' },
  { type: 'suffix', func: '毒素傷害', name: '炭疽 Anthrax', stat: '+13-25 毒素傷害於2秒內', items: '武器[33]' },
  { type: 'suffix', func: '緩毒', name: '醫治 Remedy', stat: '毒素的持續效果降低25%' },
  { type: 'suffix', func: '緩毒', name: '演進 Amelioration', stat: '毒素的持續效果降低50%', items: '項鍊[18].盔甲[18].頭飾[18].盾牌[18]' },
  { type: 'suffix', func: '緩毒', name: '反抗 Defiance', stat: '毒素的持續效果降低75%', items: '項鍊[18].盔甲[18].頭飾[18].盾牌[18]' },
  { type: 'suffix', func: '偷取生命', name: '妖巫 of the Leech', stat: '2-5% 生命於擊中時偷取' },
  { type: 'suffix', func: '偷取生命', name: '蝗蟲 of the Locust', stat: '4-7% 生命於擊中時偷取', items: '近身類武器(6-7)[20].頭飾(5-6)[47].項鍊(4-5)[57].戒指(5-6)[47]' },
  { type: 'suffix', func: '偷取生命', name: '八目鰻 of the Lamprey', stat: '6-9% 生命於擊中時偷取', items: '近身類武器(8-9)[55].頭飾(7-8)[77].項鍊(6)[85].戒指(7-8)[77]' },
  { type: 'suffix', func: '偷取法力', name: '蝙蝠 Bat', stat: '3-5% 法力於擊中時偷取' },
  { type: 'suffix', func: '偷取法力', name: '死靈 Wraith', stat: '6-7% 法力於擊中時偷取', items: '近身類武器(6-7)[21].項鍊(5-6)[58].頭飾(5-6)[58]戒指(4-5)[58]' },
  { type: 'suffix', func: '偷取法力', name: '吸血鬼 Vampire', stat: '7-9% 法力於擊中時偷取', items: '近身類武器(8-9)[56].項鍊(7-8)[78].頭飾(7-8)[78]戒指(6)[86]' },
  { type: 'suffix', func: '生命補滿', name: '重造 Regeneration', stat: '生命補滿 +3-5' },
  { type: 'suffix', func: '生命補滿', name: '重生 Regrowth', stat: '生命補滿 +6-10', items: '項鍊(6-10)[17].頭飾(6-10)[17].權杖(6-10)[17].腰帶(6-9)[55].戒指(6-9)[55]' },
  { type: 'suffix', func: '生命補滿', name: '復甦 Revivification', stat: '生命補滿 +11-15', items: '項鍊[38].頭飾[38].權杖[38]' },
  { type: 'suffix', func: '攻擊速度', name: '迅速 Readiness', stat: '10% 增加攻擊準確率' },
  { type: 'suffix', func: '攻擊速度', name: '輕快 Alacrity', stat: '20% 增加攻擊準確率', items: '武器[25].手套[43]' },
  { type: 'suffix', func: '攻擊速度', name: '敏捷 Swiftness', stat: '30% 增加攻擊準確率', items: '近身類武器[34]' },
  { type: 'suffix', func: '攻擊速度', name: '快速 Quickness', stat: '40% 增加攻擊準確率', items: '近身類武器[46]' },
  { type: 'suffix', func: '格檔機率', name: '格檔 Blocking', stat: '+10%增加格檔機率,15%快速格檔機率' },
  { type: 'suffix', func: '格檔機率', name: '偏向 Deflecting', stat: '+20%增加格檔機率,30%快速格檔機率', items: '盾牌[11]' },
  { type: 'suffix', func: '快速再度攻擊', name: '平衡 Balance', stat: '10% 快速再度攻擊' },
  { type: 'suffix', func: '快速再度攻擊', name: '均衡 Equilibrium', stat: '17% 快速再度攻擊', items: '腰帶[9].胸盔[9].盾牌[9]' },
  { type: 'suffix', func: '快速再度攻擊', name: '穩定 Stability', stat: '24% 快速再度攻擊', items: '腰帶[18].胸盔[18]' },
  { type: 'suffix', func: '物理傷害減少', name: '生命 Health', stat: '物理傷害減少 1' },
  { type: 'suffix', func: '物理傷害減少', name: '保護 Protection', stat: '物理傷害減少 2', items: '項鍊[18].胸甲[24].頭飾[18][24].戒指[18].盾牌[24]' },
  { type: 'suffix', func: '物理傷害減少', name: '吸收 Absorption', stat: '物理傷害減少 3', items: '項鍊[26].胸甲[32].頭飾[26][32].盾牌[32]' },
  { type: 'suffix', func: '物理傷害減少', name: '生命 Life', stat: '物理傷害減少 4-7', items: '項鍊(4)[35].胸甲(4-7)[41].頭飾(4)[35](4-7)[41].盾牌(4-7)[41]' },
  { type: 'suffix', func: '物理傷害減少', name: '永生 Life Everlasting', stat: '物理傷害減少 10-25', items: '項鍊[45].頭飾[45]' },
  { type: 'suffix', func: '物理傷害減少', name: '和睦 Anima', stat: '物理傷害減少 8-15', items: '胸盔[51].頭飾[51].盾牌[51]' },
  { type: 'suffix', func: '法術傷害減少', name: '防避 Warding', stat: '法術傷害減少 1' },
  { type: 'suffix', func: '法術傷害減少', name: '步哨 Sentinel', stat: '法術傷害減少 2', items: '項鍊[18].胸盔[24].頭飾[18][24].法珠[18].戒指[18].盾牌[24]' },
  { type: 'suffix', func: '法術傷害減少', name: '守衛 Guarding', stat: '法術傷害減少 3', items: '項鍊[26].胸盔[32].頭飾[26][32].法珠[26].盾牌[32]' },
  { type: 'suffix', func: '法術傷害減少', name: '否定 Negation', stat: '法術傷害減少 4-6', items: '項鍊[42].胸盔[41].頭飾[41][42].法珠[42].盾牌[41]' },
  { type: 'suffix', func: '額外金錢取得', name: '貪婪 Greed', stat: '25-40% 額外金錢取得' },
  { type: 'suffix', func: '額外金錢取得', name: '財富 Wealth', stat: '41-80% 額外金錢取得', items: '項鍊[17].腰帶[17].鞋子[17].頭飾[17].手套[17]' },
  { type: 'suffix', func: '尋寶率', name: '機會 Chance', stat: '5-15% 更佳的機會取得魔法裝備' },
  { type: 'suffix', func: '尋寶率', name: '幸運 Fortune', stat: '16-25% 更佳的機會取得魔法裝備', items: '項鍊[16].鞋子[16].頭飾[16].手套[16].戒指[42]' },
  { type: 'suffix', func: '尋寶率', name: '好運 Luck', stat: '26-35% 更佳的機會取得魔法裝備', items: '項鍊[26].鞋子[26].頭飾[26]' },
  { type: 'suffix', func: '快速施展', name: '學徒 Apprentice', stat: '10% 快速施展速度' },
  { type: 'suffix', func: '快速施展', name: '馬格斯 Magus', stat: '20% 快速施展速度', items: '頭飾[17].法珠[17].棒類[17]' },
  { type: 'suffix', func: '攻擊者受到傷害', name: '刺尖 Thorns', stat: '攻擊者受到傷害 1-3' },
  { type: 'suffix', func: '攻擊者受到傷害', name: '尖刺 Spikes', stat: '攻擊者受到傷害 4-6', items: '腰帶[21].胸盔[21].頭飾[21].盾牌[21]' },
  { type: 'suffix', func: '攻擊者受到傷害', name: '剃刀 Razors', stat: '攻擊者受到傷害 7-9', items: '胸盔[34].頭飾[34].盾牌[34]' },
  { type: 'suffix', func: '攻擊者受到傷害', name: '刀劍 Swords', stat: '攻擊者受到傷害 10-20', items: '胸盔[47].頭飾[47].盾牌[47]' },
  { type: 'suffix', func: '減少需求', name: '安逸 Ease', stat: '需求 -20%' },
  { type: 'suffix', func: '減少需求', name: '簡樸 Simplicity', stat: '需求 -30%', items: '胸盔[25].盾牌[25].武器[25]' },
  { type: 'suffix', func: '減少需求', name: '快速跑步/行走', stat: '步伐 Pacing', items: '10% 快速跑步/行走' },
  { type: 'suffix', func: '減少需求', name: '匆忙 Haste', stat: '20% 快速跑步/行走', items: '鞋子[22].頭飾[22]' },
  { type: 'suffix', func: '減少需求', name: '速度 Speed', stat: '30% 快速跑步/行走', items: '鞋子[37].頭飾[37]' },
  { type: 'suffix', func: '減少需求', name: '傳送 Transportation', stat: '30% 快速跑步/行走,耐力回復 80-90%', items: '鞋子[65]' },
  { type: 'suffix', func: '減少需求', name: '加速 Acceleration', stat: '40% 快速跑步/行走', items: '鞋子[51]' },
  { type: 'suffix', func: '擊退', name: '熊 Bear', stat: '擊退' },
  { type: 'suffix', func: '忽視目標防禦率', name: '刺穿 Piercing', stat: '忽視目標防禦率' },
  { type: 'suffix', func: '防止怪物自療', name: '下流 Vileness', stat: '防止怪物自療' },
  { type: 'suffix', func: '冰凍時間減半', name: '融解 Warmth', stat: '冰凍時間減半' },
  { type: 'suffix', func: '回復耐久度', name: '自我修復 Self-Repair', stat: '回復耐久度(3)' },
  { type: 'suffix', func: '回復耐久度', name: '回復 Fast Repair', stat: '回復耐久度(5)', items: '防具[20].武器[20]' },
  { type: 'suffix', func: '無法破壞', name: '歲月 Ages', stat: '無法破壞' },
  { type: 'suffix', func: '回復數量', name: '補充 Replenishing', stat: '自動回復數量(2)' },
  { type: 'suffix', func: '回復數量', name: '傳播 Propogation', stat: '自動回復數量(24)', items: '投擲類武器[24]' },
  { type: 'suffix', func: '回復數量', name: '生命-以角色等級決定', stat: '半人馬 Centaur', items: '+0-49 生命(以角色等級乘0.5)' },
  { type: 'suffix', func: '回復數量', name: '法力-以角色等級決定', stat: '記憶 Memory', items: '+0-49 法力(以角色等級乘0.5)' },
  { type: 'suffix', func: '回復數量', name: '生命/法力-以角色等級決定', stat: '巨象 Elephant', items: '+0-24 生命/法力(以角色等級乘0.25)' },
];

// magic2.htm — 特殊裝備字首字尾 (魔法/稀有)
export const AFFIXES2: Affix[] = [
  { type: 'prefix', func: '防禦', name: '白化之 Blanched', stat: '+5-8 防禦', items: '魔法.稀有/[1]' },
  { type: 'prefix', func: '防禦', name: '類象牙之 Eburin', stat: '+9-20 防禦', items: '魔法.稀有/[16]' },
  { type: 'prefix', func: '防禦', name: '白骨之 Bone', stat: '+21-40 防禦', items: '魔法.稀有/[32]' },
  { type: 'prefix', func: '防禦', name: '象牙之 Ivory', stat: '+41-64 防禦', items: '魔法/[64]' },
  { type: 'prefix', func: '傷害下限', name: '猩紅之 Scarlet', stat: '+1-4 最小傷害值', items: '魔法.稀有/[8]' },
  { type: 'prefix', func: '傷害下限', name: '棗紅之 Crimson', stat: '+5-8 最小傷害值', items: '魔法.稀有/[38]' },
  { type: 'prefix', func: '傷害上限', name: '紅玉之 Carbuncle', stat: '+1-5 最大傷害值', items: '魔法.稀有/[12]' },
  { type: 'prefix', func: '傷害上限', name: '胭脂之 Carmine', stat: '+6-9 最大傷害值', items: '魔法.稀有/[35]' },
  { type: 'prefix', func: '傷害上限', name: '朱砂之 Vermillion', stat: '+11-15 最大傷害值', items: '魔法/[58]' },
  { type: 'prefix', func: '傷害', name: '朱紅之 Cinnabar', stat: '+5-10% 傷害', items: '魔法.稀有/[1]' },
  { type: 'prefix', func: '傷害', name: '鐵鏽之 Rusty', stat: '+11-20% 傷害', items: '魔法.稀有/[13]' },
  { type: 'prefix', func: '傷害', name: '雄黃之 Realgar', stat: '+21-30% 傷害', items: '魔法.稀有/[45]' },
  { type: 'prefix', func: '傷害', name: '紅寶石之 Ruby', stat: '+31-40% 傷害', items: '魔法/[66]' },
  { type: 'prefix', func: '傷害轉換成法力', name: '暗褐之 Dun', stat: '+7-12% 傷害轉換成法力', items: '魔法.稀有/[7]' },
  { type: 'prefix', func: '耐力', name: '棕色之 Brown', stat: '耐力值 +10-15%', items: '魔法.稀有/[39]' },
  { type: 'prefix', func: '耐力', name: '栗色之 Chestnut', stat: '+10-15 最大耐力', items: '魔法.稀有/[1]' },
  { type: 'prefix', func: '耐力', name: '茶色之 Maroon', stat: '+16-25 最大耐力', items: '魔法.稀有/[17]' },
  { type: 'prefix', func: '準確率', name: '鎳之 Nickel', stat: '+10-20 準確率', items: '魔法.稀有/[1]' },
  { type: 'prefix', func: '準確率', name: '錫之 Tin', stat: '+21-40 準確率', items: '魔法.稀有/[8]' },
  { type: 'prefix', func: '準確率', name: '銀之 Silver', stat: '+41-60 準確率', items: '魔法.稀有/[25]' },
  { type: 'prefix', func: '準確率', name: '銀之 Argent', stat: '+61-100 準確率', items: '魔法/[44]' },
  { type: 'prefix', func: '照明', name: '光明之 Bright', stat: '+10 準確率 +1 照亮範圍', items: '魔法.稀有/[1]' },
  { type: 'prefix', func: '尋寶率', name: '祖母綠之 Emerald', stat: '+3-7% 機會取得魔法物品', items: '魔法.稀有/[25]' },
  { type: 'prefix', func: '法力', name: '鋯石之 Zircon', stat: '+5-10 法力', items: '魔法.稀有/[3]' },
  { type: 'prefix', func: '法力', name: '紅鋯石之 Jacinth', stat: '+11-15 法力', items: '魔法.稀有/[17]' },
  { type: 'prefix', func: '法力', name: '綠松石之 Turquoise', stat: '+16-20 法力', items: '魔法/[29]' },
  { type: 'prefix', func: '全抗', name: '閃耀之 Shimmering', stat: '所有抗性 +5-10', items: '魔法.稀有/[16]' },
  { type: 'prefix', func: '全抗', name: '閃閃發光之 Scintillating', stat: '所有抗性 +11-15', items: '魔法/[34]' },
  { type: 'prefix', func: '冰抗', name: '青金石之 Lapis Lazuli', stat: '抗寒 +5-15%', items: '魔法.稀有/[2]' },
  { type: 'prefix', func: '冰抗', name: '蔚藍之 Sapphire', stat: '抗寒 +16-30%', items: '魔法.稀有/[19]' },
  { type: 'prefix', func: '火抗', name: '深紅之 Garnet', stat: '抗火 +5-15%', items: '魔法.稀有/[2]' },
  { type: 'prefix', func: '火抗', name: '紅寶石之 Ruby', stat: '抗火 +16-30%', items: '魔法.稀有/[18]' },
  { type: 'prefix', func: '電抗', name: '樟腦之 Camphor', stat: '抗電 +5-15%', items: '魔法.稀有/[2]' },
  { type: 'prefix', func: '電抗', name: '龍涎香之 Ambergris', stat: '抗電 +16-30%', items: '魔法.稀有/[19]' },
  { type: 'prefix', func: '毒抗', name: '海藍之 Beryl', stat: '抗毒+5-15%', items: '魔法.稀有/[2]' },
  { type: 'prefix', func: '毒抗', name: '翠綠之 Jade', stat: '抗毒+16-30%', items: '魔法.稀有/[19]' },
  { type: 'prefix', func: '殺死敵人後取得法力', name: '光輪之 Aureolin', stat: '+1-3 點法力於殺死敵人後取得', items: '魔法.稀有/[22]' },
  { type: 'prefix', func: '額外針對惡魔', name: '鑽石之 Diamond', stat: '+25-50 準確率對抗惡魔時, +25-40% 傷害對抗惡魔時', items: '魔法.稀有/[26]' },
  { type: 'prefix', func: '額外針對不死怪物', name: '珍珠之 Pearl', stat: '+25-50 準確率對抗不死怪物時, +25-50% 傷害對抗不死怪物時', items: '魔法.稀有/[2]' },
  { type: 'suffix', func: '攻擊者受到傷害', name: '惡意 Malice', stat: '攻擊者受到傷害 1-5', items: '魔法.稀有/[37]' },
  { type: 'suffix', func: '準確率', name: '白熱 Fervor', stat: '15% 提升攻擊速度', items: '魔法/[39]' },
  { type: 'suffix', func: '傷害上限', name: '憤怒 Ire', stat: '+2-5 最大傷害', items: '魔法.稀有/[4]' },
  { type: 'suffix', func: '傷害上限', name: '怒氣 Wrath', stat: '+6-9 最大傷害', items: '魔法.稀有/[11]' },
  { type: 'suffix', func: '傷害上限', name: '屠殺的 Carnage', stat: '+11-15 最大傷害', items: '魔法/[25]' },
  { type: 'suffix', func: '傷害下限', name: '快樂 Joyfulness', stat: '+1-4 最小傷害', items: '魔法.稀有/[5]' },
  { type: 'suffix', func: '傷害下限', name: '福氣 Bliss', stat: '+5-10 最小傷害', items: '魔法.稀有/[43]' },
  { type: 'suffix', func: '快速再度攻擊', name: '真理 Truth', stat: '7% 快速再度攻擊', items: '魔法.稀有/[44]' },
  { type: 'suffix', func: '生命補滿', name: '榮譽 Honor', stat: '生命補滿 +1-4', items: '魔法.稀有/[47]' },
  { type: 'suffix', func: '額外取得金錢', name: '貪婪 Avarice', stat: '+10-30% 取得更多金錢', items: '魔法.稀有/[1]' },
  { type: 'suffix', func: '尋寶率', name: '富饒 Prosperity', stat: '+5-10% 機會取得魔法物品', items: '魔法.稀有/[26]' },
  { type: 'suffix', func: '生命', name: '靈魂 Spirit', stat: '+3-8 生命', items: '魔法.稀有/[1]' },
  { type: 'suffix', func: '生命', name: '希望 Hope', stat: '+9-20 生命', items: '魔法/[45]' },
  { type: 'suffix', func: '需求', name: '自由 Freedom', stat: '需求 -15%', items: '魔法.稀有/[1]' },
  { type: 'suffix', func: '力量', name: '精氣 Virility', stat: '+5-9 力量', items: '魔法.稀有/(5-6)[33](7-9)[50]' },
  { type: 'suffix', func: '敏捷', name: '大膽 Daring', stat: '+4-9 敏捷', items: '魔法.稀有/(4-6)[19](7-9)[36]' },
  { type: 'suffix', func: '精力', name: '知識 Knowledge', stat: '+4-9 精力', items: '魔法.稀有/(4-6)[24](7-9)[41]' },
  { type: 'suffix', func: '冰冷傷害', name: '寒冷 Frigidity', stat: '1-5 冰冷傷害 - 2 秒間', items: '魔法.稀有/[16]' },
  { type: 'suffix', func: '冰冷傷害', name: '冰刺 Icicle', stat: '+2-3 最小冰冷傷害 與 +6-10 最大冰冷傷害 - 3 秒間', items: '魔法.稀有/[37]' },
  { type: 'suffix', func: '冰冷傷害', name: '冰河的 Glacier', stat: '+4-5 最小冰冷傷害 與 +11-15 最大冰冷傷害 - 4 秒間', items: '魔法/[58]' },
  { type: 'suffix', func: '火燄傷害', name: '熱情 Passion', stat: '+1-3 最小火焰傷害 與 +6-10 最大火焰傷害', items: '魔法.稀有/[15]' },
  { type: 'suffix', func: '火燄傷害', name: '火的 Fire', stat: '+4-10 最小火焰傷害 與 +11-30 最大火焰傷害', items: '魔法.稀有/[36]' },
  { type: 'suffix', func: '火燄傷害', name: '燃燒的 Burning', stat: '+11-25 最小火焰傷害 與 +35-50 最大火焰傷害', items: '魔法/[57]' },
  { type: 'suffix', func: '閃電傷害', name: '倦怠 Ennui', stat: '+1 最小閃電傷害 與 +10-20 最大閃電傷害', items: '魔法.稀有/[15]' },
  { type: 'suffix', func: '閃電傷害', name: '閃電的 Lightning', stat: '+1 最小閃電傷害 與 +21-60 最大閃電傷害', items: '魔法.稀有/[36]' },
  { type: 'suffix', func: '閃電傷害', name: '雷電的 Thunder', stat: '+1最小閃電傷害 與 +61-100 最大閃電傷害', items: '魔法/[57]' },
  { type: 'suffix', func: '毒素傷害', name: '嫉妒 Envy', stat: '+9 [48] 最小毒素傷害 與 +26 [48-144] 最大毒素傷害', items: '魔法.稀有/[1]' },
];
